-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 06, 2023 at 04:31 PM
-- Server version: 10.4.25-MariaDB
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `zoodoo_sdgp`
--

-- --------------------------------------------------------

--
-- Table structure for table `contact_details`
--

CREATE TABLE `contact_details` (
  `ID` int(11) NOT NULL,
  `Name` varchar(100) NOT NULL,
  `Phone` varchar(100) NOT NULL,
  `Email` varchar(100) NOT NULL,
  `Comment` varchar(300) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `contact_details`
--

INSERT INTO `contact_details` (`ID`, `Name`, `Phone`, `Email`, `Comment`) VALUES
(1, 'uthpala jagodage', '0769029945', 'uthpala@gmail.com', 'hello'),
(5, 'ravidu', '0777123456789', 'ravi@gmail.com', 'gg');

-- --------------------------------------------------------

--
-- Table structure for table `food_recipes`
--

CREATE TABLE `food_recipes` (
  `Food_ID` int(11) NOT NULL,
  `Name` varchar(50) NOT NULL,
  `Ingredients` varchar(2000) NOT NULL,
  `Steps` varchar(10000) NOT NULL,
  `Image` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `food_recipes`
--

INSERT INTO `food_recipes` (`Food_ID`, `Name`, `Ingredients`, `Steps`, `Image`) VALUES
(0, 'APPLE PIE', '2 pre-made pie crusts (store-bought or homemade)\r\n6 cups of peeled, cored, and sliced apples (about 6-8 medium-sized apples)\r\n3/4 cup granulated sugar\r\n2 tablespoons all-purpose flour\r\n1 teaspoon ground cinnamon\r\n1/4 teaspoon ground nutmeg\r\n1/4 teaspoon salt\r\n1 tablespoon lemon juice\r\n2 tablespoons unsalted butter, cut into small pieces\r\n1 egg, beaten (for egg wash)\r\n1 tablespoon granulated sugar (for sprinkling)', 'Preheat your oven to 425°F (220°C).\r\n\r\nRoll out one of the pie crusts and fit it into a 9-inch pie dish. Set aside the other crust for the top.\r\n\r\nIn a large bowl, combine the sliced apples, granulated sugar, flour, cinnamon, nutmeg, salt, and lemon juice. Toss the mixture until the apples are evenly coated.\r\n\r\nPour the apple mixture into the prepared pie crust, making sure to distribute the filling evenly. Dot the top with the small pieces of butter.\r\n\r\nRoll out the second pie crust and place it over the filling. You can create a lattice design or simply lay it over the top and cut slits to allow steam to escape. Trim any excess crust and crimp the edges to seal the pie.\r\n\r\nBrush the top crust with the beaten egg, and sprinkle the tablespoon of granulated sugar over it for a golden finish.\r\n\r\nPlace the pie on a baking sheet to catch any drips, and bake in the preheated oven for 15 minutes.\r\n\r\nAfter 15 minutes, reduce the oven temperature to 375°F (190°C) and continue baking for an additional 40-50 minutes, or until the crust is golden brown and the filling is bubbly. If the edges of the crust start to brown too quickly, you can cover them with aluminum foil.\r\n\r\nOnce the pie is done, remove it from the oven and let it cool on a wire rack for at least 2 hours before serving. This will allow the filling to set.\r\n\r\nServe the apple pie warm or at room temperature, and you can enjoy it as is or with a scoop of vanilla ice cream or a dollop of whipped cream.', 'https://www.cubesnjuliennes.com/wp-content/uploads/2020/11/Apple-Pie.jpg'),
(1, 'BEET SALAD', '\r\n3 medium-sized beets\r\n1/2 cup crumbled feta cheese\r\n1/4 cup chopped walnuts (optional)\r\n2 tablespoons balsamic vinegar\r\n2 tablespoons extra-virgin olive oil\r\n2 tablespoons fresh lemon juice\r\n2 tablespoons chopped fresh parsley\r\nSalt and pepper to taste\r\nMixed salad greens (optional, for serving)', 'Start by cooking the beets. You can either roast or boil them. To roast, preheat your oven to 400°F (200°C). Trim off the beet greens, leaving about an inch of the stems intact. Wrap each beet in aluminum foil and place them on a baking sheet. Roast for about 45-60 minutes, or until the beets are tender when pierced with a knife. If boiling, place the trimmed beets in a large pot of boiling water and cook for about 30-40 minutes, or until tender. Once cooked, let the beets cool before handling.\r\n\r\nOnce the beets are cool enough to handle, peel off the skins using your hands or a knife. The skins should come off easily. Cut the beets into bite-sized cubes or slices and place them in a mixing bowl.\r\n\r\nAdd the crumbled feta cheese and chopped walnuts (if using) to the bowl with the beets.\r\n\r\nIn a separate small bowl, whisk together the balsamic vinegar, olive oil, lemon juice, chopped parsley, salt, and pepper until well combined.\r\n\r\nPour the dressing over the beet mixture and gently toss until everything is well coated.\r\n', 'https://thestayathomechef.com/wp-content/uploads/2013/04/Beet-Salad-3-e1520389016838.jpg'),
(2, 'CARROT CAKE', '2 cups all-purpose flour\r\n2 cups granulated sugar\r\n1 teaspoon baking powder\r\n1/2 teaspoon baking soda\r\n1/2 teaspoon salt\r\n1 teaspoon ground cinnamon\r\n1/2 teaspoon ground nutmeg\r\n1/2 cup vegetable oil\r\n4 large eggs\r\n2 cups grated carrots\r\n1/2 cup crushed pineapple, drained\r\n1/2 cup chopped walnuts (optional)\r\n1 teaspoon vanilla extract\r\nFor the cream cheese frosting:\r\n8 oz (225g) cream cheese, softened\r\n1/2 cup unsalted butter, softened\r\n4 cups powdered sugar\r\n1 teaspoon vanilla extract\r\n\r\nOptional garnish:\r\nAdditional chopped walnuts or grated carrots', 'Preheat your oven to 350°F (175°C). Grease and flour a 9x13-inch baking pan or two 9-inch round cake pans.\r\n\r\nIn a large mixing bowl, whisk together the flour, sugar, baking powder, baking soda, salt, cinnamon, and nutmeg.\r\n\r\nAdd the vegetable oil and eggs to the dry ingredients, and mix until well combined.\r\n\r\nStir in the grated carrots, crushed pineapple, chopped walnuts (if using), and vanilla extract. Mix until the ingredients are evenly distributed.\r\n\r\nPour the batter into the prepared cake pan(s) and smooth the top with a spatula.\r\n\r\nBake in the preheated oven for 30-35 minutes for a 9x13-inch pan or 25-30 minutes for round pans, or until a toothpick inserted into the center comes out clean.\r\n\r\nRemove the cake(s) from the oven and let them cool in the pan(s) for about 10 minutes. Then transfer the cake(s) to a wire rack to cool completely.\r\n\r\nWhile the cake is cooling, prepare the cream cheese frosting. In a mixing bowl, beat the softened cream cheese and butter together until creamy and smooth.\r\n\r\nGradually add the powdered sugar, one cup at a time, while continuing to beat the mixture. Add the vanilla extract and beat until the frosting is light and fluffy.\r\n\r\nOnce the cake has cooled completely, spread the cream cheese frosting evenly over the top and sides of the cake.\r\n\r\nIf desired, garnish the cake with additional chopped walnuts or grated carrots.\r\n', 'https://natashaskitchen.com/wp-content/uploads/2023/03/Carrot-Cake-SQ1.jpg'),
(3, 'CHEESE CAKE', '2 cups graham cracker crumbs\r\n1/4 cup granulated sugar\r\n1/2 cup unsalted butter, melted\r\n\r\nFor the filling:\r\n32 oz (900g) cream cheese, softened\r\n1 1/2 cups granulated sugar\r\n4 large eggs\r\n1 teaspoon vanilla extract\r\n1/2 cup sour cream\r\n1/4 cup all-purpose flour\r\n\r\nFor the topping (optional):\r\n1 cup sour cream\r\n2 tablespoons granulated sugar\r\n1/2 teaspoon vanilla extract', '\r\nPreheat your oven to 325°F (160°C). Grease a 9-inch springform pan with butter or cooking spray.\r\n\r\nIn a mixing bowl, combine the graham cracker crumbs, granulated sugar, and melted butter for the crust. Mix until the crumbs are evenly coated with butter.\r\n\r\nPress the crumb mixture into the bottom of the prepared springform pan, creating an even layer. Use the back of a spoon or the bottom of a glass to firmly press the crumbs down.\r\n\r\nIn a large mixing bowl, beat the softened cream cheese and granulated sugar together until smooth and creamy.\r\n\r\nAdd the eggs, one at a time, beating well after each addition. Make sure to scrape down the sides of the bowl to ensure even mixing.\r\n\r\nStir in the vanilla extract, sour cream, and flour. Mix until all the ingredients are well incorporated and the batter is smooth.\r\n\r\nPour the cream cheese filling over the crust in the springform pan. Smooth the top with a spatula.\r\n\r\nPlace the pan in the preheated oven and bake for approximately 55-60 minutes, or until the edges are set but the center is slightly jiggly.\r\n\r\nRemove the cheesecake from the oven and let it cool in the pan on a wire rack for about 10 minutes.\r\n\r\nIn the meantime, prepare the optional topping by combining the sour cream, granulated sugar, and vanilla extract in a small bowl. Mix until well combined.\r\n\r\nGently spread the sour cream topping over the slightly cooled cheesecake.\r\n\r\nReturn the cheesecake to the oven and bake for an additional 5 minutes.\r\n\r\nRemove the cheesecake from the oven and let it cool completely in the pan on a wire rack.\r\n\r\nOnce completely cooled, refrigerate the cheesecake for at least 4 hours, or overnight, to allow it to set.', 'https://natashaskitchen.com/wp-content/uploads/2023/03/Carrot-Cake-SQ1.jpg'),
(4, 'CHOCOLATE CAKE', '2 cups all-purpose flour\r\n2 cups granulated sugar\r\n3/4 cup unsweetened cocoa powder\r\n1 1/2 teaspoons baking powder\r\n1 1/2 teaspoons baking soda\r\n1 teaspoon salt\r\n2 large eggs\r\n1 cup whole milk\r\n1/2 cup vegetable oil\r\n2 teaspoons vanilla extract\r\n1 cup boiling water\r\n\r\nFor the chocolate frosting:\r\n1 cup unsalted butter, softened\r\n3 1/2 cups powdered sugar\r\n1/2 cup unsweetened cocoa powder\r\n1/2 cup whole milk\r\n2 teaspoons vanilla extract', 'Preheat your oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.\r\n\r\nIn a large mixing bowl, combine the flour, sugar, cocoa powder, baking powder, baking soda, and salt. Mix well to ensure they are evenly combined.\r\n\r\nAdd the eggs, milk, vegetable oil, and vanilla extract to the dry ingredients. Mix on medium speed using an electric mixer for about 2 minutes until well combined.\r\n\r\nReduce the speed to low and slowly add the boiling water to the batter. Mix until the water is fully incorporated. The batter will be thin, but that\'s normal.\r\n\r\nPour the batter evenly into the prepared cake pans.\r\n\r\nBake in the preheated oven for 30 to 35 minutes, or until a toothpick inserted into the center of the cakes comes out clean.\r\n\r\nRemove the cakes from the oven and allow them to cool in the pans for about 10 minutes. Then, transfer them to a wire rack to cool completely.\r\n\r\nWhile the cakes are cooling, prepare the chocolate frosting. In a large bowl, cream the butter until it becomes light and fluffy. Gradually add the powdered sugar and cocoa powder, alternating with the milk. Mix well after each addition. Finally, stir in the vanilla extract and beat until the frosting is smooth and creamy.\r\n\r\nOnce the cakes have cooled completely, spread a layer of chocolate frosting on top of one cake layer. Place the second cake layer on top and frost the top and sides of the cake with the remaining chocolate frosting.\r\n\r\nYou can decorate the cake as desired with chocolate shavings, sprinkles, or any other toppings you prefer.\r\n\r\nSlice and serve the delicious homemade chocolate cake!', 'https://drivemehungry.com/wp-content/uploads/2022/07/strawberry-cheesecake-11.jpg'),
(5, 'CHOCOLATE MOUSSE', '8 ounces (225 grams) of high-quality dark chocolate, chopped\r\n4 large eggs, separated\r\n1/4 cup (50 grams) of granulated sugar\r\n1/2 teaspoon of vanilla extract\r\nPinch of salt\r\n1 cup (240 milliliters) of heavy cream\r\n\r\nOptional: whipped cream and chocolate shavings for garnish', 'Melt the chocolate: Place the chopped chocolate in a heatproof bowl and set it over a pan of simmering water. Stir the chocolate until it melts completely and becomes smooth. Remove the bowl from the heat and let it cool slightly.\r\n\r\nBeat the egg yolks: In a separate bowl, beat the egg yolks with half of the sugar until they become pale and creamy. This can be done using an electric mixer or by hand with a whisk.\r\n\r\nIncorporate the melted chocolate: Gradually pour the melted chocolate into the beaten egg yolks while continuously whisking. Stir until well combined and smooth.\r\n\r\nWhip the egg whites: In another clean bowl, beat the egg whites and salt until soft peaks form. Gradually add the remaining sugar while continuing to beat the egg whites until they form stiff peaks.\r\n\r\nFold in the egg whites: Gently fold the beaten egg whites into the chocolate mixture using a spatula. Make sure to do this slowly and carefully to maintain the light and airy texture.\r\n\r\nWhip the cream: In a separate bowl, whip the heavy cream until it reaches a soft peak consistency.\r\n\r\nCombine the whipped cream: Fold the whipped cream into the chocolate mixture, again using a gentle folding motion until everything is well combined.\r\n\r\nChill and set: Transfer the chocolate mousse mixture into individual serving glasses or a large serving bowl. Cover and refrigerate for at least 2 hours, or until set.\r\n', 'https://celebratingsweets.com/wp-content/uploads/2021/01/Easy-Chocolate-Mousse-1-2.jpg'),
(7, 'DONUTS', 'For the donuts:\r\n\r\n2 3/4 cups (345 grams) of all-purpose flour\r\n1/4 cup (50 grams) of granulated sugar\r\n2 1/4 teaspoons of active dry yeast\r\n1/2 teaspoon of salt\r\n1/2 cup (120 milliliters) of milk\r\n1/4 cup (56 grams) of unsalted butter, melted\r\n2 large eggs\r\n1 teaspoon of vanilla extract\r\nVegetable oil, for frying\r\n\r\nFor the glaze:\r\n\r\n2 cups (250 grams) of powdered sugar\r\n1/4 cup (60 milliliters) of milk\r\n1 teaspoon of vanilla extract\r\nFood coloring or sprinkles (optional)', 'Proof the yeast: In a small bowl, combine the yeast and 1 teaspoon of sugar with warm milk. Let it sit for about 5 minutes until the mixture becomes frothy.\r\n\r\nMix the dry ingredients: In a large mixing bowl, whisk together the flour, remaining sugar, and salt.\r\n\r\nCombine the wet ingredients: In a separate bowl, whisk together the melted butter, eggs, and vanilla extract. Add the yeast mixture and whisk again.\r\n\r\nMake the dough: Pour the wet ingredients into the dry ingredients and stir until a dough forms. Knead the dough on a lightly floured surface for about 5 minutes until it becomes smooth and elastic.\r\n\r\nLet the dough rise: Place the dough in a greased bowl, cover it with a clean kitchen towel, and let it rise in a warm place for about 1 to 1.5 hours, or until it doubles in size.\r\n\r\nRoll out and cut the donuts: After the dough has risen, punch it down and roll it out on a floured surface to about 1/2 inch (1.27 cm) thickness. Use a donut cutter or a round biscuit cutter to cut out donut shapes. If you don\'t have a cutter, you can use a glass for the outer shape and a smaller one or a bottle cap for the inner circle.\r\n\r\nLet the donuts rise again: Place the cut-out donuts onto a baking sheet lined with parchment paper. Cover them with a clean kitchen towel and let them rise for another 30 minutes.\r\n\r\nHeat the oil: In a deep pot or a deep fryer, heat vegetable oil to about 350°F (175°C).\r\n\r\nFry the donuts: Carefully add a few donuts to the hot oil, being careful not to overcrowd the pot. Fry for about 2-3 minutes per side until golden brown. Use a slotted spoon or tongs to transfer the fried donuts to a paper towel-lined plate to remove excess oil. Repeat the process until all the donuts are fried.\r\n\r\nPrepare the glaze: In a bowl, whisk together powdered sugar, milk, and vanilla extract until smooth. If desired, add food coloring to the glaze for different colors. You can also dip the glazed donuts into sprinkles while the glaze is still wet.\r\n\r\nGlaze the donuts: Dip each donut into the glaze, making sure to coat both sides. Place the glazed donuts on a wire rack to allow any excess glaze to drip off.', 'https://www.thespruceeats.com/thmb/PGh87G5Z6xe_wNfLYQsm7AuHo2U=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/unicorn-doughnuts-4773240-hero-01-9e468efed0f64d8a8fdc103f31cc4d8a.jpg'),
(8, 'FRIED RICE', '3 cups of cooked rice (preferably leftover rice, chilled)\r\n2 tablespoons of vegetable oil\r\n1 cup of cooked protein (chicken, shrimp, or tofu), diced or shredded (optional)\r\n1/2 cup of diced vegetables (carrots, peas, bell peppers, onions, etc.)\r\n2 cloves of garlic, minced\r\n2 eggs, lightly beaten\r\n2 tablespoons of soy sauce\r\n1 tablespoon of oyster sauce (optional)\r\n1/2 teaspoon of sesame oil\r\nSalt and pepper to taste\r\nOptional toppings: sliced green onions, chopped cilantro, sesame seeds', 'Heat the oil: Heat the vegetable oil in a large skillet or wok over medium-high heat.\r\n\r\nSauté the protein and vegetables: If using cooked protein, sauté it in the hot oil until heated through. If using raw protein, cook it first before adding the vegetables. Add the diced vegetables to the skillet and stir-fry for a few minutes until they are slightly tender. You can add vegetables according to your preference.\r\n\r\nAdd garlic and eggs: Push the protein and vegetables to one side of the skillet and add the minced garlic to the other side. Cook for about 30 seconds until fragrant, then add the lightly beaten eggs to the skillet. Stir the eggs gently until they are scrambled and cooked through.\r\n\r\nAdd the rice: Add the cooked rice to the skillet, breaking up any clumps with a spatula. Mix the rice with the protein, vegetables, and eggs until well combined.\r\n\r\nSeason the fried rice: Drizzle the soy sauce, oyster sauce (if using), and sesame oil over the rice. Toss everything together until the rice is evenly coated with the sauces. Season with salt and pepper to taste. Be careful not to add too much salt if your soy sauce is already salty.\r\n\r\nStir-fry and combine: Stir-fry the fried rice for a few minutes, allowing the flavors to meld together and the rice to heat through. Make sure everything is well combined.\r\n\r\nServe: Remove the skillet from heat and transfer the fried rice to serving plates or bowls. Garnish with sliced green onions, chopped cilantro, and sesame seeds, if desired.', 'https://lifeloveandgoodfood.com/wp-content/uploads/2023/03/chicken_fried_rice00032a-1200x1200-1.jpg'),
(9, 'FROZEN YOGURT', '4 cups (900 grams) of plain yogurt (Greek yogurt works well)\r\n1/2 cup (100 grams) of granulated sugar (adjust to taste)\r\n1 teaspoon of vanilla extract\r\nOptional: Fresh fruit, such as berries or sliced peaches, for flavoring', 'Prepare the yogurt: In a large bowl, combine the plain yogurt, sugar, and vanilla extract. Stir until the sugar is fully dissolved and the mixture is well combined.\r\n\r\nOptional: If you\'re adding fresh fruit for flavoring, wash and chop the fruit into small pieces. You can add about 1-2 cups of fruit to the yogurt mixture, depending on your preference. Stir the fruit into the yogurt mixture until evenly distributed.\r\n\r\nChill the mixture: Cover the bowl with plastic wrap and refrigerate the mixture for at least 1 hour to allow the flavors to meld together and the mixture to cool.\r\n\r\nFreeze the yogurt: After chilling, pour the yogurt mixture into an ice cream maker. Follow the manufacturer\'s instructions for freezing, typically running the machine for about 20-25 minutes or until the mixture reaches a soft-serve consistency.\r\n\r\nTransfer to a container: Once the frozen yogurt has reached the desired consistency, transfer it to an airtight container. You can enjoy the frozen yogurt immediately as a soft-serve texture or continue to freeze it for a firmer consistency.\r\n\r\nHardening in the freezer: If you prefer a firmer frozen yogurt, place the container in the freezer for a few hours or until it reaches the desired firmness. Remember to cover the container tightly to prevent freezer burn.', 'https://www.melskitchencafe.com/wp-content/uploads/2021/07/strawberry-frozen-yogurt5.jpg'),
(10, 'GARLIC BREAD', '1 French baguette or Italian bread loaf\r\n1/2 cup (113 grams) of unsalted butter, softened\r\n4 cloves of garlic, minced\r\n2 tablespoons of fresh parsley, finely chopped (optional)\r\n1/4 teaspoon of salt\r\n1/4 teaspoon of black pepper\r\nOptional: Shredded mozzarella cheese', 'Preheat the oven: Preheat your oven to 375°F (190°C).\r\n\r\nPrepare the garlic butter: In a small bowl, mix together the softened butter, minced garlic, fresh parsley (if using), salt, and black pepper. Stir until well combined.\r\n\r\nSlice the bread: Take the French baguette or Italian bread loaf and slice it lengthwise, splitting it in half.\r\n\r\nSpread the garlic butter: Using a butter knife, spread the garlic butter mixture evenly on the cut sides of the bread.\r\n\r\nOptional: If you prefer cheesy garlic bread, sprinkle a generous amount of shredded mozzarella cheese on top of the garlic butter.\r\n\r\nReassemble the bread: Place the two halves of the bread back together, forming a loaf shape.\r\n\r\nWrap in foil: Wrap the loaf in aluminum foil, ensuring it is sealed tightly.\r\n\r\nBake in the oven: Place the foil-wrapped loaf on a baking sheet and bake in the preheated oven for about 15-20 minutes, or until the bread is heated through and the butter is melted.\r\n\r\nOptional: For a crispier texture, open the foil during the last 5 minutes of baking and continue baking without the foil.', 'https://www.sipandfeast.com/wp-content/uploads/2022/07/garlic-bread-recipe-snippet.jpg'),
(11, 'HOT DOG', '4 hot dog buns\r\n4 beef hot dogs\r\nCondiments of your choice (ketchup, mustard, mayonnaise, relish, onions, sauerkraut, etc.)', 'Preheat the grill or stovetop: If using a grill, preheat it to medium-high heat. If using a stovetop, preheat a large skillet or griddle over medium heat.\r\n\r\nGrill or cook the hot dogs: Place the hot dogs on the grill or in the skillet. Cook them for about 5-7 minutes, turning occasionally, until they are heated through and have grill marks or are lightly browned.\r\n\r\nWarm the buns: If desired, you can lightly toast the hot dog buns by placing them on the grill for a minute or in a toaster. This step is optional, but it adds a nice crunch to the buns.\r\n\r\nAssemble the hot dogs: Place each hot dog inside a bun. Add your preferred condiments such as ketchup, mustard, mayonnaise, relish, onions, sauerkraut, or any other toppings of your choice.', 'https://media-cldnry.s-nbcnews.com/image/upload/newscms/2020_27/1586836/hotdogs-te-square-200702.jpg'),
(12, 'ICE CREAM', '2 cups heavy cream\r\n1 cup whole milk\r\n3/4 cup granulated sugar\r\n1 tablespoon pure vanilla extract', 'In a mixing bowl, combine the heavy cream and whole milk.\r\n\r\nGradually add the granulated sugar to the cream and milk mixture, stirring until the sugar is completely dissolved.\r\n\r\nStir in the vanilla extract and mix well.\r\nPour the mixture into an ice cream maker.\r\n\r\nFollow the manufacturer\'s instructions for your specific ice cream maker. This typically involves churning the mixture for about 20-30 minutes or until it reaches a soft-serve consistency.\r\n\r\nIf you prefer a firmer texture, transfer the ice cream to an airtight container and place it in the freezer for a few hours or until it reaches the desired consistency.\r\n\r\nServe the ice cream in bowls or cones, and feel free to add your favorite toppings or sauces.', 'https://www.allrecipes.com/thmb/pH8hoFfytcOT9XVK1DSmxv3L0OU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/140877-easy-eggless-strawberry-ice-cream-ddmfs-3x4-1-092e4d11b59049c8b3843014ea3c57f2.jpg'),
(13, 'LASAGNA', 'For the meat sauce:\r\n\r\n1 pound (450 grams) of ground beef\r\n1 onion, diced\r\n3 cloves of garlic, minced\r\n1 can (14 ounces or 400 grams) of crushed tomatoes\r\n1 can (6 ounces or 170 grams) of tomato paste\r\n1 can (8 ounces or 227 grams) of tomato sauce\r\n2 teaspoons of dried basil\r\n2 teaspoons of dried oregano\r\n1 teaspoon of sugar\r\nSalt and pepper to taste\r\n\r\nFor the cheese filling:\r\n\r\n2 cups (500 grams) of ricotta cheese\r\n1/2 cup (50 grams) of grated Parmesan cheese\r\n1/4 cup (15 grams) of fresh parsley, chopped\r\n1 large egg\r\nSalt and pepper to taste\r\n\r\nOther ingredients:\r\n\r\n12 lasagna noodles, cooked according to package instructions\r\n3 cups (300 grams) of shredded mozzarella cheese', 'Preheat the oven: Preheat your oven to 375°F (190°C).\r\n\r\nPrepare the meat sauce: In a large skillet or saucepan, brown the ground beef over medium heat. Add the diced onion and minced garlic, and cook until the onion is translucent and the beef is fully cooked. Drain any excess fat from the pan.\r\n\r\nAdd the tomato sauce and seasonings: To the cooked beef, add the crushed tomatoes, tomato paste, tomato sauce, dried basil, dried oregano, sugar, salt, and pepper. Stir well to combine. Let the sauce simmer for about 15-20 minutes, allowing the flavors to meld together.\r\n\r\nPrepare the cheese filling: In a separate bowl, combine the ricotta cheese, grated Parmesan cheese, chopped parsley, egg, salt, and pepper. Mix well until fully combined.\r\n\r\nAssemble the lasagna: Spread a thin layer of meat sauce on the bottom of a 9x13-inch baking dish. Place 4 cooked lasagna noodles on top, slightly overlapping to cover the bottom. Spread half of the cheese filling evenly over the noodles, followed by a layer of meat sauce. Sprinkle a generous amount of shredded mozzarella cheese on top. Repeat the layers with 4 more noodles, the remaining cheese filling, meat sauce, and mozzarella cheese. Finish with a final layer of 4 lasagna noodles, meat sauce, and mozzarella cheese.\r\n\r\nBake the lasagna: Cover the baking dish with aluminum foil, ensuring it is sealed tightly to trap the heat. Bake in the preheated oven for 25 minutes. Then, remove the foil and bake for an additional 15-20 minutes until the cheese is melted, bubbly, and lightly golden.\r\n\r\nLet it rest: Remove the lasagna from the oven and let it rest for 10-15 minutes before slicing and serving. This allows the lasagna to set and makes it easier to portion.', 'https://thecozycook.com/wp-content/uploads/2022/04/Lasagna-Recipe-f.jpg'),
(14, 'OMELETTE', '3 large eggs\r\n2 tablespoons of milk or water\r\nSalt and pepper to taste\r\n1 tablespoon of butter or cooking oil\r\nOptional fillings: Shredded cheese, diced vegetables (such as bell peppers, onions, mushrooms), cooked bacon or ham, fresh herbs (such as parsley or chives)', 'Beat the eggs: In a bowl, crack the eggs and whisk them together until the yolks and whites are fully combined. Add the milk or water and whisk again until well incorporated. Season with salt and pepper to taste.\r\n\r\nPrepare the fillings: If using any fillings, prepare them by chopping or shredding them into small pieces. Cook any raw vegetables or meats in advance if necessary.\r\n\r\nHeat the skillet: Place a non-stick skillet over medium heat. Add the butter or oil and let it melt or heat up.\r\n\r\nPour and cook the eggs: Once the butter or oil is hot, pour the beaten eggs into the skillet. Let the eggs cook undisturbed for a few seconds until the edges start to set.\r\n\r\nAdd the fillings: Sprinkle the desired fillings evenly over one half of the omelette. Be mindful not to overfill, as it may make folding the omelette more challenging.\r\n\r\nFold the omelette: Using a spatula, carefully lift the empty half of the omelette and fold it over the filling side, creating a half-moon shape. Press down gently with the spatula to seal the omelette.\r\n\r\nCook and finish: Reduce the heat to low and continue cooking the folded omelette for another 1-2 minutes, or until the fillings are heated through and the omelette is cooked to your desired level of doneness. If you prefer a slightly runny center, cook it for a shorter time.', 'https://www.seriouseats.com/thmb/5oPmAF7IggGPRKSmqtccGeeR_-M=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2020__06__20200602-western-denver-omelette-daniel-gritzer-8-20ef3336fd4b44f68987badfde08a71a.jpg'),
(15, 'PANCAKES', '1 cup all-purpose flour\r\n2 tablespoons granulated sugar\r\n2 teaspoons baking powder\r\n1/2 teaspoon salt\r\n1 cup milk\r\n1 large egg\r\n2 tablespoons melted butter (plus more for greasing the pan)\r\nOptional: additional ingredients like chocolate chips, blueberries, or sliced bananas\r\n', 'In a mixing bowl, whisk together the flour, sugar, baking powder, and salt.\r\n\r\nIn a separate bowl, whisk together the milk, egg, and melted butter.\r\n\r\nPour the wet ingredients into the dry ingredients and stir until just combined.\r\n\r\nIt\'s okay if there are a few lumps in the batter.\r\n\r\nIf desired, you can add in additional ingredients like chocolate chips, blueberries, or sliced bananas at this point and gently fold them into the batter.\r\n\r\nHeat a large non-stick skillet or griddle over medium heat. Add a small amount of butter to grease the surface.\r\n\r\nScoop about 1/4 cup of batter onto the skillet for each pancake. Cook until bubbles form on the surface, then flip the pancake and cook for an additional 1-2 minutes, or until golden brown.\r\n\r\nTransfer the cooked pancakes to a plate and cover with a towel to keep them warm. Repeat the process with the remaining batter, adding more butter to the pan as needed.\r\n\r\nServe the pancakes with your favorite toppings, such as maple syrup, fresh fruit, whipped cream, or a sprinkle of powdered sugar.', 'https://hurrythefoodup.com/wp-content/uploads/2015/03/easy-omelette-recipe-recipe-card-image.jpg'),
(16, 'PIZZA', 'For the dough:\r\n\r\n2 ¼ teaspoons (1 packet) of active dry yeast\r\n1 teaspoon of sugar\r\n1 cup of warm water (around 110°F/43°C)\r\n2 ½ cups of all-purpose flour\r\n2 tablespoons of olive oil\r\n1 teaspoon of salt\r\n\r\nFor the sauce:\r\n\r\n1 can (14 ounces or 400 grams) of crushed tomatoes\r\n2 cloves of garlic, minced\r\n1 teaspoon of dried basil\r\n1 teaspoon of dried oregano\r\nSalt and pepper to taste\r\nFor the toppings:\r\n\r\nShredded mozzarella cheese\r\nDesired toppings such as pepperoni, sliced vegetables, cooked sausage, mushrooms, etc.', 'Prepare the dough:\r\n\r\nIn a small bowl, combine the warm water, sugar, and yeast. Stir gently and let it sit for about 5 minutes until the yeast becomes frothy.\r\nIn a large mixing bowl, combine the flour and salt. Make a well in the center and pour in the yeast mixture and olive oil.\r\nStir the mixture with a spoon until a dough starts to form.\r\nTransfer the dough to a lightly floured surface and knead it for about 5-7 minutes until it becomes smooth and elastic.\r\nPlace the dough in a greased bowl, cover it with a clean kitchen towel, and let it rise in a warm place for about 1-2 hours until it doubles in size.\r\nPrepare the sauce:\r\n\r\nIn a small saucepan, combine the crushed tomatoes, minced garlic, dried basil, dried oregano, salt, and pepper.\r\nSimmer the sauce over low heat for about 15-20 minutes to allow the flavors to meld together. Adjust the seasoning to your taste.\r\nPreheat the oven:\r\n\r\nPreheat your oven to the highest temperature it can reach, typically around 475°F (245°C) or higher. If you have a pizza stone, place it in the oven to preheat as well.\r\nRoll out the dough:\r\n\r\nOnce the dough has risen, punch it down and transfer it to a lightly floured surface.\r\nRoll out the dough into your desired pizza shape and thickness. You can make one large pizza or divide the dough to make multiple smaller ones.\r\nAssemble the pizza:\r\n\r\nTransfer the rolled-out dough to a pizza stone, baking sheet, or pizza pan.\r\nSpread a layer of the prepared sauce evenly over the dough, leaving a small border around the edges.\r\nSprinkle a generous amount of shredded mozzarella cheese over the sauce.\r\nAdd your desired toppings on top of the cheese. Be creative and use any combination of toppings you prefer.\r\nBake the pizza:\r\n\r\nPlace the pizza in the preheated oven and bake for about 12-15 minutes, or until the crust is golden brown and the cheese is bubbly and melted.\r\nServe and enjoy:\r\n\r\nRemove the pizza from the oven and let it cool for a few minutes.\r\nSlice the pizza into wedges and serve it hot.\r\nFeel free to garnish with fresh basil, grated Parmesan cheese, or a drizzle of olive oil if desired.', 'https://www.allrecipes.com/thmb/0xH8n2D4cC97t7mcC7eT2SDZ0aE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/6776_Pizza-Dough_ddmfs_2x1_1725-fdaa76496da045b3bdaadcec6d4c5398.jpg'),
(17, 'RAMEN', '4 cups chicken or vegetable broth\r\n2 cups water\r\n2 packs of ramen noodles (discard the seasoning packets if you prefer to make your own broth)\r\n2 tablespoons soy sauce\r\n1 tablespoon miso paste (optional)\r\n1 tablespoon sesame oil\r\n2 cloves garlic, minced\r\n1-inch piece of ginger, grated\r\nSliced green onions, for garnish\r\nSliced boiled eggs, for garnish\r\nSliced cooked meat or tofu, for garnish (optional)\r\nSliced vegetables (such as carrots, mushrooms, bok choy), for garnish (optional)\r\nNori seaweed sheets, torn into small pieces, for garnish (optional)', 'In a large pot, heat the sesame oil over medium heat. Add the minced garlic and grated ginger, and sauté for about 1-2 minutes until fragrant.\r\n\r\nAdd the chicken or vegetable broth and water to the pot. If you\'re not using the seasoning packets from the ramen noodles, you can add soy sauce and miso paste to the broth for extra flavor.\r\n\r\nBring the broth to a boil, then reduce the heat and let it simmer for about 10-15 minutes to allow the flavors to meld together.\r\n\r\nWhile the broth is simmering, prepare the ramen noodles according to the package instructions. Drain and set aside.\r\n\r\nOnce the broth is ready, taste and adjust the seasoning as desired. You can add more soy sauce or miso paste for extra flavor.\r\n\r\nTo assemble the ramen bowls, divide the cooked ramen noodles into serving bowls. Ladle the hot broth over the noodles.\r\n\r\nGarnish with sliced green onions, sliced boiled eggs, cooked meat or tofu, sliced vegetables, and torn nori seaweed sheets.', 'https://inquiringchef.com/wp-content/uploads/2022/11/Easy-Miso-Ramen_square-0723.jpg'),
(18, 'SAMOSA', 'For the dough:\r\n\r\n2 cups (250 grams) all-purpose flour\r\n1/2 teaspoon of salt\r\n2 tablespoons of vegetable oil\r\nWater (as needed)\r\n\r\nFor the filling:\r\n\r\n2 medium potatoes, boiled and mashed\r\n1/2 cup (75 grams) green peas, boiled and slightly mashed\r\n1 small onion, finely chopped\r\n2 green chilies, finely chopped (adjust to taste)\r\n1 teaspoon of grated ginger\r\n1 teaspoon of cumin seeds\r\n1 teaspoon of coriander powder\r\n1/2 teaspoon of turmeric powder\r\n1/2 teaspoon of garam masala\r\nSalt to taste\r\n2 tablespoons of vegetable oil\r\nFresh coriander leaves, chopped (optional)\r\n\r\nFor frying:\r\n\r\nVegetable oil for deep frying', '\r\nPrepare the dough:\r\n\r\nIn a mixing bowl, combine the all-purpose flour, salt, and vegetable oil. Mix well until the oil is evenly distributed.\r\nGradually add water, a little at a time, and knead to form a firm and smooth dough. The dough should not be too soft or too stiff. Cover the dough and set it aside for 15-20 minutes.\r\nPrepare the filling:\r\n\r\nHeat 2 tablespoons of vegetable oil in a pan over medium heat.\r\nAdd the cumin seeds and allow them to splutter.\r\nAdd the chopped onions, grated ginger, and green chilies. Sauté until the onions turn translucent.\r\nAdd the coriander powder, turmeric powder, and garam masala. Stir and cook for a minute.\r\nAdd the boiled and mashed potatoes, mashed peas, and salt. Mix well to combine all the ingredients.\r\nCook the mixture for 2-3 minutes, stirring occasionally. Remove from heat and let the filling cool. Add chopped fresh coriander leaves if desired.\r\nShape and fill the samosas:\r\n\r\nDivide the dough into small lemon-sized balls.\r\nTake one ball and roll it out into a thin circle on a lightly floured surface.\r\nCut the circle in half. Take one half and fold it into a cone shape, overlapping the edges and sealing them with a little water.\r\nFill the cone with 1-2 tablespoons of the prepared filling, ensuring not to overstuff it.\r\nApply a little water on the open edges of the cone and press to seal the samosa. Repeat the process with the remaining dough and filling.\r\nFry the samosas:\r\n\r\nHeat vegetable oil in a deep pan or kadai for frying over medium heat.\r\nOnce the oil is hot, gently slide a few samosas into the oil, taking care not to overcrowd the pan.\r\nFry the samosas until they turn golden brown and crispy on all sides. This usually takes about 8-10 minutes.\r\nRemove the fried samosas from the oil using a slotted spoon and drain excess oil on a paper towel.\r\nServe and enjoy:\r\n\r\nServe the samosas hot with chutney, such as mint chutney or tamarind chutney, or tomato ketchup.\r\nSamosas are best enjoyed fresh, but they can be stored in an airtight container for a day or two and reheated in an oven or toaster oven before serving.', 'https://www.cubesnjuliennes.com/wp-content/uploads/2020/08/Best-Indian-Punjabi-Samosa-Recipe.jpg'),
(19, 'WAFFLES', '2 cups all-purpose flour\r\n2 tablespoons granulated sugar\r\n1 tablespoon baking powder\r\n1/2 teaspoon salt\r\n1 3/4 cups milk\r\n1/2 cup unsalted butter, melted\r\n2 large eggs\r\n1 teaspoon vanilla extract', 'Preheat your waffle iron according to the manufacturer\'s instructions.\r\n\r\nIn a mixing bowl, whisk together the flour, sugar, baking powder, and salt.\r\n\r\nIn a separate bowl, whisk together the milk, melted butter, eggs, and vanilla extract.\r\n\r\nPour the wet ingredients into the dry ingredients and stir until just combined. \r\nIt\'s okay if there are a few lumps in the batter.\r\nLightly grease the preheated waffle iron with non-stick cooking spray or a small amount of melted butter.\r\n\r\nSpoon the batter onto the center of the waffle iron, spreading it evenly. \r\nThe amount of batter will depend on the size of your waffle iron.\r\nClose the lid of the waffle iron and cook according to the manufacturer\'s instructions, typically 3-5 minutes or until the waffles are golden brown and crisp.\r\n\r\nCarefully remove the waffles from the iron and place them on a wire rack to cool slightly. Avoid stacking them to prevent them from becoming soggy.\r\n\r\nRepeat the process with the remaining batter until all the waffles are cooked.\r\n\r\nServe the waffles warm with your favorite toppings, such as maple syrup, fresh fruit, whipped cream, or a sprinkle of powdered sugar.', 'https://bakeitwithlove.com/wp-content/uploads/2022/05/bisquick-waffles-sq.jpg'),
(6, 'CUPCAKES', 'For the cupcakes:\r\n\r\n1 1/2 cups (190 grams) of all-purpose flour\r\n1 1/2 teaspoons of baking powder\r\n1/4 teaspoon of salt\r\n1/2 cup (113 grams) of unsalted butter, softened\r\n1 cup (200 grams) of granulated sugar\r\n2 large eggs\r\n1 teaspoon of vanilla extract\r\n1/2 cup (120 milliliters) of milk\r\n\r\nFor the frosting:\r\n\r\n1/2 cup (113 grams) of unsalted butter, softened\r\n2 cups (250 grams) of powdered sugar\r\n1-2 tablespoons of milk or heavy cream\r\n1 teaspoon of vanilla extract\r\nFood coloring (optional)\r\n', 'Preheat the oven: Preheat your oven to 350°F (175°C). Line a cupcake tray with paper liners.\r\n\r\nPrepare the cupcakes: In a medium bowl, whisk together the flour, baking powder, and salt. Set aside.\r\n\r\nCream the butter and sugar: In a large mixing bowl, cream together the softened butter and granulated sugar until light and fluffy. You can use an electric mixer or do it by hand with a whisk.\r\n\r\nAdd eggs and vanilla: Add the eggs one at a time to the butter-sugar mixture, beating well after each addition. Stir in the vanilla extract.\r\n\r\nAlternate adding dry ingredients and milk: Gradually add the dry ingredient mixture to the butter-sugar mixture, alternating with the milk. Begin and end with the dry ingredients, mixing just until combined after each addition. Be careful not to overmix.\r\n\r\nFill the cupcake liners: Spoon the cupcake batter into the lined cupcake tray, filling each liner about two-thirds full.\r\n\r\nBake the cupcakes: Place the cupcake tray in the preheated oven and bake for 18-20 minutes, or until a toothpick inserted into the center of a cupcake comes out clean. Remove from the oven and let them cool completely on a wire rack.\r\n\r\nPrepare the frosting: In a mixing bowl, beat the softened butter until creamy. Gradually add the powdered sugar, mixing well after each addition. Stir in the vanilla extract. If the frosting is too thick, add milk or heavy cream, one tablespoon at a time, until the desired consistency is reached. You can also add food coloring if desired.\r\n\r\nFrost the cupcakes: Once the cupcakes are completely cooled, frost them using a piping bag or a butter knife. You can get creative with different frosting designs and decorations.', 'https://www.allrecipes.com/thmb/GsldgnTeewAv5eEqoxQ7E1iAKO8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/157877-vanilla-cupcakes-ddmfs-2X1-0399-1b671dfd598548b1b0339076d062a758.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `contact_details`
--
ALTER TABLE `contact_details`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `contact_details`
--
ALTER TABLE `contact_details`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
